### ISSUE TITLE
Language tool doesn't work. Gives following errors:

### ISSUE THREAD

**Issue by dsedov** [adamvoss/vscode-languagetool#18]
Mac OSX 10.13.3
Java 9.0.3
VSCode 1.21.0
In development mode, while trying to see what the problem is found the following log file:
vscode-languagetool-languageserver.log:

App.main
Mar 07, 2018 7:42:52 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification
Mar 07, 2018 7:42:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "languageTool": {
        "language": "en",
        "enabled": true
      }
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at net.loomchild.segment.srx.io.Srx2SaxParser.<init>(Srx2SaxParser.java:173)
	at org.languagetool.tokenizers.SrxTools.createSrxDocument(SrxTools.java:51)
	at org.languagetool.tokenizers.SRXSentenceTokenizer.<init>(SRXSentenceTokenizer.java:53)
	at org.languagetool.tokenizers.SimpleSentenceTokenizer.<init>(SimpleSentenceTokenizer.java:37)
	at org.languagetool.Language.<clinit>(Language.java:60)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.languagetool.Languages.createLanguageObjects(Languages.java:110)
	at org.languagetool.Languages.getAllLanguages(Languages.java:96)
	at org.languagetool.Languages.<clinit>(Languages.java:38)
	at LanguageToolLanguageServer.setLanguage(LanguageToolLanguageServer.java:206)
	at LanguageToolLanguageServer.setLanguage(LanguageToolLanguageServer.java:202)
	at LanguageToolLanguageServer.access$400(LanguageToolLanguageServer.java:19)
	at LanguageToolLanguageServer$2.didChangeConfiguration(LanguageToolLanguageServer.java:180)
	... 16 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 30 more

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory (file:/Users/dennissedov/.vscode/extensions/adamvoss.vscode-languagetool-3.8.0/lib/languagetool-languageserver/build/install/languagetool-languageserver/lib/org.eclipse.lsp4j.jsonrpc-0.2.0.jar) to constructor java.util.Collections$EmptyList()
WARNING: Please consider reporting this to the maintainers of org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by m0ru** [comment]
same here q.q

vscode 1.23.0-insider
openjdk 10.0.1
ubuntu 18.04

**Comment by pdjstone** [comment]
It looks like this is caused by the following bug in the LS4J library which this project uses: https://github.com/eclipse/lsp4j/issues/157.

That bug is now fixed so in theory all that is needed to fix this is to update the LS4J [dependency](https://github.com/languagetool-language-server/languagetool-languageserver/blob/master/build.gradle) to use the latest version. However, it seems that this project is no longer maintained?

A workaround would be to use Java 8 instead.

**Comment by davidlday** [comment]
Please see #25.
